"""Frozen configuration for the four-hour spot dual-trend candidate."""

STATUS = "FROZEN_FOR_PROSPECTIVE_PAPER_TEST"
FROZEN_DATE = "2026-07-28"

SYMBOL = "BTCUSDT"
MARKET = "spot"
TIMEFRAME = "4h"
TIMEZONE = "UTC"

EMA_FAST = 24
EMA_SLOW = 168
MOMENTUM_LOOKBACK = 120
TREND_SMA = 300
LONG_EXPOSURE = 1.0
FLAT_EXPOSURE = 0.0

FEE = 0.001
SLIPPAGE = 0.0005
MIN_TRADE_FRAC = 0.01
INITIAL_CAPITAL = 10_000.0
BARS_PER_YEAR = 6 * 365
MAX_GAP_BARS = 1
LIVE_TRADING_APPROVED = False
