"""Frozen 4h BTC paper-candidate configuration. Any change requires re-validation."""

STATUS = "FROZEN_FOR_PROSPECTIVE_PAPER_TEST"
FROZEN_DATE = "2026-07-27"

SYMBOL = "BTCUSDT"
MARKET = "perpetual"
TIMEFRAME = "4h"
TIMEZONE = "UTC"

MA_BARS = 250
VOL_WINDOW_BARS = 60
TARGET_ANNUAL_VOL = 0.40
MIN_EFFECTIVE_EXPOSURE = 0.25
MAX_LONG_EXPOSURE = 2.0
MAX_SHORT_EXPOSURE = 0.50
REBALANCE_BARS = 42
REBALANCE_ANCHOR_UTC = "2019-09-08T16:00:00+00:00"
EXECUTION_DELAY_BARS = 1

FEE = 0.0004
SLIPPAGE = 0.0003
MAINTENANCE_MARGIN = 0.005
BARS_PER_YEAR = 6 * 365

# Live deployment is explicitly not authorized by this configuration.
LIVE_TRADING_APPROVED = False
